use_default_settings: true

search:
  formats:
    - html
    - json

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "2217668895c03a62d60570a2c5c4c3af59368fdcec7c3ec3bdd45317fd3aec24"
  limiter: false
